Update build recipes to work on modern Linux
EdgeApp/airbitz-core pull request #32
Opened 2024-03-19 21:14 UTC by swansontec

- Work around -Wno-implicit-int issue breaking autoconf scripts.
- Prevent cURL from trying to use more system libraries
- Work around C++ standard library change affecting libbitcoin
- Work around alignment issue affecting libsodium
- Use our self-compiled version of protoc, instead of the system one.

2024-03-24 23:49 UTC, paullinator requested changes
Everything checks out as reasonable changes except the removal of the `ALIGN(64)` and `CRYPTO_ALIGN(64)` directives. Any reference online to what issues libsodium had with these?

2024-03-25 00:07 UTC, swansontec commented
The alignment issue comes from giving the compiler conflicting instructions. You pack 48-bit values together tightly while aligning them on a 64-bit boundary. Either the alignment or the packing has to go. I chose to axe the alignment because that was the simplest edit. The consequence is that we are going to do an un-aligned load, which is legal but slow on x86.

Actually fixing the problem correctly requires deeper refactors to the libsodium sources, to get the structure sizes lined up again. I was trying to hack a working build without upgrading dependencies, but I that might be the only option here, if the hacks aren't OK.

2024-03-25 02:12 UTC, paullinator approved these changes

2024-03-25 17:58 UTC, swansontec commented
I ran "make check" in the libsodium folder, and everything passed without the alignment.

2024-03-25 17:58 UTC, merged